const newParagrah = document.createElement('p');
newParagrah.innerText = 'Added with Javascript';
document.body.appendChild(newParagrah);
const newImage = document.createElement('img');
newImage.setAttribute('src', 'images/animals.jfif');
newImage.setAttribute('alt', 'Puppy Image');
document.body.appendChild(newImage);
const newSection = document.createElement('section');
newSection.innerHTML = '<h2>CSE 121B</h2> <p>Welcome to javascript language</p>';
document.body.appendChild(newSection);